replicaCount: 2

image:
  repository: final-devops-app
  tag: "local"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 5001

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
